### ISSUE TITLE
highscore webpage

### ISSUE THREAD

**Issue by PeterSenkel** [VE3NEA/MorseRunner#4]
dear alex,

i really like using MorseRunner a lot and i am pretty sure many people do. what i don't understand is why the high score page responds with a 404. i am sure this has something to do with not being able to maintain it anymore. i would offer you to take over. i am pretty sure we could find a way so that you only would have to change the link in your source code. please let me now if you are interested. 

best regards and thanks a lot for your effort
peter

**Comment by VE3NEA** [comment]
Hi Peter,

The scores table has been removed because Morse Runner is now open source, and anyone can post any score she wants. This table 
no longer has any value.

Alex

**Comment by PeterSenkel** [comment]
thanks for replying instantly.
i got your point here. i'll think about it. so i close this issue.
vy 73
